FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 10000

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["Zo.csproj", "./"]
RUN dotnet restore "Zo.csproj"
COPY . .
RUN dotnet build "Zo.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Zo.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Zo.dll"]